import { HOST_IP } from './HostConfig';

/**
 * Returns the IP address generated by the 'set-ip.ts' script.
 * We prioritize this over runtime detection which can be unreliable.
 */
export const getPCIpAddress = (): string | null => {
    if (HOST_IP && HOST_IP.length > 0) {
        console.log(`[IP] Using Configured Host IP: ${HOST_IP}`);
        return HOST_IP;
    }
    return null;
};

/**
 * Returns the WebSocket URL using the automatically detected IP.
 * Defaults to localhost if detection fails.
 * @param isTestMode If true, connects to Test Server (8002). Else Main Server (8001).
 */
export const getWebSocketUrl = (isTestMode: boolean = false): string => {
    const ip = getPCIpAddress();
    const host = ip || '0.0.0.0'; // Fallback to last known good IP

    const port = isTestMode ? "8002" : "8001";
    const endpoint = isTestMode ? "Lumen-test-ws" : "Lumen-ws";

    return `ws://${host}:${port}/${endpoint}`;
};
