import { NativeModules } from 'react-native';
import { HOST_IP } from './HostConfig';

/**
 * Automatically detects the IP address of the packager (PC) when running in development mode.
 * This is useful for connecting to backend services running on the same machine as the bundler.
 * 
 * @returns {string | null} The IP address of the PC, or null if not found.
 */
export const getPCIpAddress = (): string | null => {
    // 1. Priority: Check for injected value from HostConfig.ts (generated by set-ip.sh)
    if (HOST_IP) {
        console.log(`[IP] Using Configured Host IP: ${HOST_IP}`);
        return HOST_IP;
    }

    // 2. Fallback: Try NativeModules
    const scriptURL = NativeModules.SourceCode.scriptURL;
    if (!scriptURL) {
        return null;
    }

    // The scriptURL is typically in the format: http://192.168.x.x:8081/index.bundle?...
    const address = scriptURL.split('://')[1].split('/')[0];
    const ip = address.split(':')[0];

    return ip;
};

/**
 * Returns the WebSocket URL using the automatically detected IP.
 * Defaults to localhost if detection fails.
 * @param isTestMode If true, connects to Test Server (8002). Else Main Server (8001).
 */
export const getWebSocketUrl = (isTestMode: boolean = false): string => {
    const ip = getPCIpAddress();
    const host = ip || '172.16.1.196'; // Fallback to last known good IP

    const port = isTestMode ? "8002" : "8001";
    const endpoint = isTestMode ? "Lumen-test-ws" : "Lumen-ws";

    return `ws://${host}:${port}/${endpoint}`;
};
