const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
    console.log("🔄 Detecting Host IP...");

    // Execute the bash script to get IP
    // Note: We use the absolute path relative to this script
    // Use process.cwd() since we run this from project root via npm scripts
    const projectRoot = process.cwd();
    const scriptPath = path.join(projectRoot, 'scripts', 'get-ip.sh');

    // Ensure script is executable
    execSync(`chmod +x "${scriptPath}"`);

    const ip = execSync(`"${scriptPath}"`).toString().trim();

    if (!ip) {
        console.error("❌ Failed to detect IP Address");
        process.exit(1);
    }

    console.log(`✅ Detected Host IP: ${ip}`);

    // Path to HostConfig.ts
    const configPath = path.join(projectRoot, 'src/utils/HostConfig.ts');

    // Content to write
    const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/set-ip.ts
 */
export const HOST_IP: string = "${ip}";
`;

    fs.writeFileSync(configPath, content);
    console.log(`✅ Updated HostConfig.ts`);

} catch (error) {
    console.error("❌ Error setting IP:", error);
    process.exit(1);
}
