#!/bin/bash

# Get the first IP address provided by hostname -I
HOST_IP=$(hostname -I | awk '{print $1}')

if [ -z "$HOST_IP" ]; then
    echo "Error: Could not detect IP address."
    exit 1
fi

echo "Detected Host IP: $HOST_IP"

# Path to the React Native Config File (TypeScript)
CONFIG_FILE="src/utils/HostConfig.ts"
# Ensure the directory exists
mkdir -p "src/utils"

# Write the TypeScript file
cat > "$CONFIG_FILE" <<EOF
/**
 * Auto-generated by scripts/set-ip.sh
 * Do not edit manually. This file is overwritten on build.
 */
export const HOST_IP = "$HOST_IP";
export const API_URL = "http://$HOST_IP:8001";
EOF

echo "Updated $CONFIG_FILE with HOST_IP=$HOST_IP"
